### PR TITLE
Update redis backend with fixes V1.1

### PR DESCRIPTION
**Pull request by PatrickGleeson**
The changes from V1 with a few test/bug fixes.

- Fix `RedisBackend.store_idempotency_key()` to match the spec outlined in the parent `Backend`: If the key already exists, return `True`, when the key doesn't exist, return `False`
- Fix `RedisBackend.__init__` to take in `expiry` (The `@dataclass` decorator won't override an existing `__init__`)
- Adjust poetry extras to install `redis` not `aioredis`
- Re-add the `client` test fixture as a async fixture

### CODE REVIEW

**Comment by PatrickGleeson** [comment]
The 3.7 tests are failing because of the changes to `importlib_metadata` and `pluggy` not being able to handle it.
And the pyproject.toml specifies this requires python 3.8 or greater anyways...

**Comment by sondrelg** [comment]
Yeah I support dropping support for 3.8 initially. If anyone really needs it we could add it later :+1:

**Comment by sondrelg** [comment]
Finally, is this right? a5389fda6e9eccaf2c8236fb4610f3ecedeb1a5b

**Comment by sondrelg** [comment]
I'll put out a release candidate now in case you need one, and release v0.2.0 tomorrow once you've seen the comments :slightly_smiling_face:

**Comment by PatrickGleeson** [comment]
Yes, that is the name/email to use for me.
And this is great, release v0.2.0 whenever you can.

**Comment by sondrelg** [comment]
Released now :rocket: We have a slack channel for the snok org if you use slack by the way. Want to join that to discuss next steps for a v1 release? If so, should I send an invite to the same email as mentioned above? If you don't use slack, no worries, we can open an issue instead :+1: 

https://pypi.org/project/asgi-idempotency-header/

**Comment by sondrelg** [comment]
That being said, it's midnight here so I'll sign off for now. Thanks for putting together the PR :clap:

**Pull request merged**
